const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');
const { createHmac } = require('node:crypto');
const { SERVICES, workspaceManifests, buildPlan, deploymentLockfile } = require('../../scripts/docker/build-runtime.cjs');
const { localEnvironment } = require('../../scripts/docker/init-env.cjs');
const root = path.resolve(__dirname, '../..');
const entries = workspaceManifests(root);

for (const [service, directory] of Object.entries(SERVICES)) {
  test(`${service}: runtime dependencies build before their consumers`, () => {
    const plan = buildPlan(entries, `@du/${service}`);
    assert.equal(plan.at(-1), `@du/${service}`);
    for (const name of plan) {
      for (const [dependency, version] of Object.entries(entries.get(name).manifest.dependencies ?? {})) {
        if (version.startsWith('workspace:')) assert.ok(plan.indexOf(dependency) < plan.indexOf(name));
      }
    }
    // Connector is a worker SDK test dependency, and must never enter worker builds.
    if (directory.startsWith('businesses/')) assert.ok(!plan.includes('@du/connector'));
  });
  test(`${service}: legacy Dockerfile stays in sync with canonical targets`, () => {
    const canonical = fs.readFileSync(path.join(root, 'Dockerfile'), 'utf8').replace(/\r\n/g, '\n');
    const generated = fs.readFileSync(path.join(root, directory, 'Dockerfile'), 'utf8').replace(/\r\n/g, '\n');
    assert.equal(generated, `${canonical}\n# Generated by scripts/docker/sync-dockerfiles.cjs.\nFROM ${service} AS service\n`);
  });
}

test('build planner refuses dependency cycles and missing workspace packages', () => {
  const graph = new Map([
    ['a', { manifest: { dependencies: { b: 'workspace:*' } } }],
    ['b', { manifest: { dependencies: { a: 'workspace:*' } } }],
  ]);
  assert.throws(() => buildPlan(graph, 'a'), /cycle/);
  graph.delete('b');
  assert.throws(() => buildPlan(graph, 'a'), /Missing workspace dependency/);
});

test('portable deployment preserves every locked version and importer', () => {
  const original = fs.readFileSync(path.join(root, 'pnpm-lock.yaml'), 'utf8');
  const prepared = deploymentLockfile(original);
  assert.equal(prepared.slice(prepared.indexOf('overrides:')), original.slice(original.indexOf('overrides:')));
  assert.equal(deploymentLockfile(prepared), prepared);
  assert.throws(() => deploymentLockfile('lockfileVersion: 9\n'), /settings are missing/);
});

test('local credentials encode identical grant bytes and signed, expiring identity', () => {
  const env = localEnvironment(1700000000000);
  assert.equal(Buffer.byteLength(env.INVOCATION_GRANT_SECRET), 32);
  assert.deepEqual(Buffer.from(env.INVOCATION_GRANT_SECRET), Buffer.from(env.CONNECTOR_INVOCATION_GRANT_SECRET, 'base64'));
  assert.notEqual(env.RUNTIME_TOKEN, env.ADMIN_TOKEN);
  const [header, payload, signature] = env.CONNECTOR_SERVICE_TOKEN.split('.');
  assert.equal(signature, createHmac('sha256', Buffer.from(env.SERVICE_IDENTITY_SECRET, 'base64'))
    .update(`${header}.${payload}`).digest('base64url'));
  const claims = JSON.parse(Buffer.from(payload, 'base64url'));
  assert.equal(claims.aud, 'connector');
  assert.deepEqual(claims.scopes, ['connector:invoke']);
  assert.equal(claims.exp, 1700000000 + 86400);
});

const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'du-compose-regression-'));
const envFile = path.join(temporary, 'test.env');
fs.writeFileSync(envFile, Object.entries({ ...localEnvironment(), ORCHESTRATOR_PORT: '24100',
  ADMIN_SHELL_PORT: '24101', CONNECTOR_PORT: '24180' }).map(([k, v]) => `${k}=${v}`).join('\n'));
const wrappers = ['docker-compose.yml', ...Object.values(SERVICES).map(dir => `${dir}/docker-compose.yml`)];
const cleanEnv = { ...process.env };
// Keep the model independent of the developer's shell env and credentials.
for (const file of fs.readdirSync(path.join(root, 'compose'))) {
  const fragment = fs.readFileSync(path.join(root, 'compose', file), 'utf8');
  for (const match of fragment.matchAll(/\$\{([A-Z][A-Z0-9_]*)/g)) delete cleanEnv[match[1]];
}
function compose(filename, environmentFile = envFile) {
  return spawnSync('docker', ['compose', '--env-file', environmentFile, '-f', filename, 'config', '--format', 'json'],
    { cwd: root, env: cleanEnv, encoding: 'utf8' });
}
for (const filename of wrappers) {
  test(`${filename}: model resolves builds, ports, startup order and shared networks`, () => {
    const result = compose(filename);
    assert.equal(result.status, 0, result.stderr);
    const model = JSON.parse(result.stdout);
    assert.equal(model.services.postgres.ports, undefined);
    assert.equal(model.services.valkey.ports, undefined);
    for (const [name, service] of Object.entries(model.services)) {
      assert.equal(service.container_name, undefined);
      if (service.build) {
        assert.equal(path.resolve(service.build.context), root);
        assert.equal(service.build.dockerfile, 'Dockerfile');
        assert.ok(Object.hasOwn(SERVICES, service.build.target));
      }
      if (service.ports) {
        for (const port of service.ports) assert.equal(port.host_ip, '127.0.0.1');
        if (name === 'orchestrator') {
          assert.equal(service.environment.PORT, '3000');
          assert.equal(service.environment.ORCHESTRATOR_PORT, undefined);
          assert.deepEqual(service.ports.map(p => [p.target, p.published]), [[3000, '24100'], [3001, '24101']]);
          assert.equal(service.depends_on.migrate.condition, 'service_completed_successfully');
          assert.equal(service.environment.AUTO_MIGRATE, 'false');
        }
        if (name === 'connector') {
          assert.equal(service.environment.PORT, '8080');
          assert.equal(service.environment.CONNECTOR_PORT, undefined);
          assert.equal(service.ports[0].published, '24180');
        }
      }
      if (name === 'document-core' || name === 'lc-checker') {
        const connector = model.services.connector;
        assert.ok(Object.keys(service.networks).some(n => Object.hasOwn(connector.networks, n)));
        assert.equal(service.environment.CONNECTOR_URL, 'http://connector:8080');
        assert.equal(service.depends_on.connector.condition, 'service_healthy');
      }
      if (['document-core', 'lc-checker', 'example-review'].includes(name)) {
        const identities = JSON.parse(model.services.orchestrator.environment.WORKER_IDENTITY_TOKENS_BY_BUSINESS);
        assert.equal(service.environment.RUNTIME_TOKEN, identities[name]);
        assert.notEqual(service.environment.RUNTIME_TOKEN, model.services.orchestrator.environment.ADMIN_TOKEN);
      }
    }
    if (filename === 'docker-compose.yml') assert.equal(Object.keys(model.services).length, 8);
  });
}
test('missing secrets refuse startup instead of using sample production passwords', () => {
  const empty = path.join(temporary, 'empty.env');
  fs.writeFileSync(empty, '');
  const result = compose('docker-compose.yml', empty);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /POSTGRES_PASSWORD/);
});

process.on('exit', () => {
  fs.unlinkSync(envFile);
  const empty = path.join(temporary, 'empty.env');
  if (fs.existsSync(empty)) fs.unlinkSync(empty);
  fs.rmdirSync(temporary);
});
