/** Static production event labels; unknown/free-form messages are hidden. */
export const SAFE_LOG_MESSAGES = new Set<string>([
  'connector shutdown failed',
  'connector startup failed',
  'example-review worker startup failed',
  'lc-checker worker startup failed',
  'worker shutdown failed',
  "Document Core Worker successfully registered and listening",
  "Failed to parse worker environment configuration",
  "Shutting down worker gracefully...",
  "Starting Document Core Worker service",
  "Worker failed during graceful shutdown",
  "Worker failed to start",
  "Worker shutdown completed cleanly",
  "[admin-bff] settings read did not match the settings DTO",
  "[admin-bff] unhandled request error",
  "[admin-bff] upstream call failed",
  "[admin-bff] upstream returned a non-JSON success body",
  "[admin-shell] DU_ADMIN_WEB ignored (expected 1/true or an absolute path)",
  "[admin-shell] DU_ADMIN_WEB_ROUTES ignored unknown route names",
  "[admin-shell] admin web index unreadable",
  "[admin-shell] admin web mount enabled",
  "[admin-shell] admin web mount enabled but bundle is missing",
  "[admin-shell] deferred render error",
  "[admin-shell] deferred section render error",
  "[admin-shell] security event",
  "[admin-shell] unhandled request error",
  "[example-review] review operation failed",
  "admin shell listening",
  "ambiguous runtime report; ending delivery for redelivery",
  "artifact encryption enabled",
  "artifact integrity scan tick skipped: previous scan still running",
  "completion replayed (already terminal)",
  "database is up-to-date",
  "delivery fenced at claim (busy/terminal)",
  "delivery for unregistered handler kind",
  "fail report fenced",
  "grace period expired with in-flight deliveries; lease recovery will handle them",
  "handler aborted after lease loss; no report sent",
  "handler failed",
  "lease lost during heartbeat; aborting context",
  "migration command cannot start",
  "migration command failed",
  "migration status",
  "migration verification passed",
  "migrations applied",
  "orchestrator listening",
  "orchestrator startup failed",
  "retry scheduled by handler",
  "schema verification passed",
  "step checkpoint replay",
  "task yielded",
  "temp workspace sweep failed",
  "temp workspace sweep removed stale dirs",
  "unhandled ingress error",
  "unhandled listener error",
  "unhandled request error",
  "unknown migration command",
  "worker heartbeat failed",
  "workspace-reference query uncertain; treating dir as referenced"
]);
